import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

// Components
import Footer from "../components/Footer/Footer";
import Header from "../components/Header/Header";
import SignUp from "../components/SignUp/SignUp";
import FlexDiv from "../components/FlexDiv/FlexDiv";
import HeroBlock from "../components/HeroBlock/HeroBlock";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>XYZ coding test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <SignUp />
      <main className={styles.main}>
        <FlexDiv>
          <div className={styles.column}>
            <h1>What&apos;s a TLD?</h1>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. In at
              tellus nulla. Fusce vehicula et ex eget luctus. Proin pharetra
              felis eget{" "}
              <a href="#" style={{ color: "var(--color-blue-2)" }}>
                lectus maximus
              </a>{" "}
              feugiat. Praesent eu nunc nec dui dignissim ultricies et et mi.
              Vivamus nulla velit, lacinia nec molestie a, viverra sed felis.
              Integer finibus libero ligula, at ornare arcu rutrum suscipit.
              Integer fermentum fermentum urna vel posuere.
            </p>
            <h2>New Top Level Domains</h2>
            <p>
              New Top Level Domains Nam molestie facilisis nibh, ut tincidunt
              arcu lacinia non. Nam quam ligula, finibus ac elit ut, cursus
              sodales est. Cras feugiat risus neque, sit amet porta lorem congue
              non. Morbi volutpat ligula a leo ornare malesuada. Suspendisse nec
              hendrerit massa. Nullam fermentum est non est consequat, at mollis
              elit ullamcorper.
            </p>
          </div>
          <div className={styles.column}>
            <div className={styles.image}>
              <Image
                src="/computer.jpg"
                layout="fill"
                objectFit="cover"
              ></Image>
            </div>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. In at
              tellus nulla. Fusce vehicula et ex eget luctus. Proin pharetra
              felis eget lectus maximus feugiat. Praesent eu nunc nec dui
              dignissim ultricies et et mi. Vivamus nulla velit, lacinia nec
              molestie a, viverra sed felis. Integer finibus libero ligula, at
              ornare arcu rutrum suscipit.{" "}
              <a href="#">Integer fermentum(hover style)</a> fermentum urna vel
              posuere.
            </p>
          </div>
        </FlexDiv>

        <HeroBlock header="How to get a great domain name">
          <div className={styles.childdiv}>
            <div className={styles.number}>1</div>
          </div>
          <div className={styles.childdiv}>
            <div className={styles.number}>1</div>
          </div>
        </HeroBlock>
      </main>
      <Footer />
    </div>
  );
}
